#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

max_todo_count=50
todo_count=$(grep -sinr todo $WORKSPACE_ROOT/src/ | wc -l)

if [ $((todo_count)) -eq 0 ]; then
    echo "${GREEN}No TODOS detected${NC}"
    exit 0
fi
echo "Number of TODOs: ${RED}$todo_count${NC}"
grep -sinr todo $WORKSPACE_ROOT/src/

if [ $((todo_count)) -gt $((max_todo_count)) ]; then
    echo "Too many TODOs!"
    echo ""
    echo "Please resolve them before pushing."
  exit 1
fi

exit 0