#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

result=$(grep -n -r --include="*.cc" --include="*.h"  --include="*.txt" --include="*.yaml" --include="Doxyfile" --include="*.md" --include="*.sh" "<<<<<<< HEAD" $WORKSPACE_ROOT)

if [ -z "$result" ]
then
  echo "${GREEN}No CONFLICTS detected${NC}"
  exit 0
else
  echo "${RED}Found CONFLICTS that still need resolution:${NC}"
  echo "$result"
  exit 1
fi
