name: "Ubuntu Intel"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    # Map a step output to a job output
    outputs:
      package_name: ${{ steps.package.outputs.DEB_PACKAGE }}
    steps:
      - uses: actions/checkout@v3
      - name: Apt Update
        run: sudo apt-get update

      - name: Apt Install
        run: |
          sudo ./scripts/init_build_machine.sh

      - name: CMake and Build
        run: mkdir build && cd build && cmake -DEXAMPLES=ON -DBUILD_QT6=ON -DGST_SUPPORT=ON .. && make

      - name: Install
        run: cd build && sudo make install
