name: "Ubuntu 20.04 Intel"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    # Map a step output to a job output
    outputs:
      package_name: ${{ steps.package.outputs.DEB_PACKAGE }}
    steps:
      - uses: actions/checkout@v3
      - name: Apt Update
        run: sudo apt-get update

      - name: Apt Install
        run: |
          sudo ./scripts/init_build_machine.sh 20.04

      - name: CMake and Build
        run: mkdir build && cd build && cmake -DEXAMPLES=ON -DBUILD_QT6=OFF -DGST_SUPPORTED=ON .. && make

      - name: Package
        run: |
          cd build
          cpack
          echo "DEB_PACKAGE=$(ls *.deb)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${DEB_PACKAGE}
          path: build/${DEB_PACKAGE}
