name: "Ubuntu 24.04 Intel"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04

    # Map a step output to a job output
    outputs:
      package_name: ${{ steps.package.outputs.DEB_PACKAGE }}
    steps:
      - uses: actions/checkout@v3
      - name: Apt Update
        run: sudo apt-get update

      - name: Apt Install
        run: |
          sudo ./scripts/init_build_machine.sh 22.04

      - name: CMake and Build
        run: mkdir build && cd build && cmake -DEXAMPLES=ON -DBUILD_QT6=ON -DGST_SUPPORTED=ON -DBUILD_RUST=ON .. && make

      - name: Install
        run: cd build && cpack

      - name: Package
        id: package
        run: |
          cd build
          echo "::set-output name=DEB_PACKAGE::$(ls *.deb)"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.DEB_PACKAGE }}
          path: ${{ build/steps.package.outputs.DEB_PACKAGE }}

